spring.application.name=api-gateway
server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.main.web-application-type=reactive
jwt.secret=talentsync-simple-secret-key-change-this-in-production

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins[0]=http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[3]=OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[4]=DELETE
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders[0]=Authorization
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders[1]=Content-Type

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.server.webflux.routes[1].id=job-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://job-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/jobs/**
spring.cloud.gateway.server.webflux.routes[2].id=application-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://application-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/applications/**
spring.cloud.gateway.server.webflux.routes[3].id=recruitement-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://application-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/recruitment/**
spring.cloud.gateway.server.webflux.routes[4].id=candidate-profile
spring.cloud.gateway.server.webflux.routes[4].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/candidates/**
